---
spring:
  datasource:
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://localhost/distributorntwkdb
         username: root
         password: Jinesh@123
  jpa:
    show_sql: true
    generate-ddl: false
...
           